# Generated by Django 5.2 on 2025-04-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airinua', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackrequest',
            options={'ordering': ['-created_at'], 'verbose_name': "Заявка на зворотній зв'язок", 'verbose_name_plural': "Заявки на зворотній зв'язок"},
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='contact_method',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('call', 'Подзвонити')], max_length=10, verbose_name="Спосіб зв'язку"),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='airinua.product', verbose_name='Товар'),
        ),
    ]
